### ISSUE TITLE
血量条宽度问题

### ISSUE THREAD

**Issue by Heliumw** [NERvGear/SAO-Utils#18]
能不能允许调整血量条宽度？现在这个6个字母都显示不下.....
By the way，不考虑使用一些免费/开放使用（我不了解）的图标库吗...现在的图标真的好少啊啊啊啊

**Comment by GPBeta** [comment]
emmmmmmmmm, 设计变化有点大
![20191021190332](https://user-images.githubusercontent.com/13177262/67200153-93b3f800-f435-11e9-8b66-ecb9df84f8c9.png)
图标的话后面会加一些通用的，不过目前自带 200 个组还不够吗？

**Comment by SeasonG-CN** [comment]
> emmmmmmmmm, 设计变化有点大
> ![20191021190332](https://user-images.githubusercontent.com/13177262/67200153-93b3f800-f435-11e9-8b66-ecb9df84f8c9.png)
> 图标的话后面会加一些通用的，不过目前自带 200 个组还不够吗？

**头都笑歪了**
