### ISSUE TITLE
SAOUtils stops working after the computer resumes from hibernation.

### ISSUE THREAD

**Issue by visualDust** [NERvGear/SAO-Utils#2]
哦哈呦。瓦达西一个高三生。早上爬起床准备去上学，电脑掀开盖发现SAOUtils不动了。然后我还原了几次翻车（划掉）现场，发现休眠可以让SAOUtils（至少在我的电脑上）死掉。好像是假死。不过我说了我要上学去了就没打开Engine细查，没有更多细节，不好意思。
```
计算机配置
Microsoft Windows [版本 10.0.17134.706]
RAM 8GB
CPU IntelCore i7 7500U
GPU IntelHDGraphics 620 （别问我为什么SAOUtils为啥在我电脑上这么卡）
```
---
我溜了！大大们辛苦了。（Manual Funny）

**Comment by GPBeta** [comment]
是不是 Exp 1 版本？

**Comment by visualDust** [comment]
是的是的（暴露了在学校看手机）

**Comment by GPBeta** [comment]
下载 [coreplugin.zip](https://github.com/NERvGear/SAO-Utils/files/3121772/coreplugin.zip)

解压覆盖到 SAO Utils\Qt\qml\NERvGear 里面试试

**Comment by visualDust** [comment]
估计得等85个小时左右。  
我还关在学校里呢现在
![VisualDust一脸乖巧.jpg](https://is5-ssl.mzstatic.com/image/thumb/Purple30/v4/f2/84/a5/f284a5ee-016d-a223-44cd-55cb97c9ac7b/source/512x512bb.jpg)

**Comment by cxx1234** [comment]
Exp1 覆盖安装后正常(～￣▽￣)～唤醒计算机后不再假死

**Comment by visualDust** [comment]
嗯我搞到了一台电脑我试试看
呃....coreplugin....
system call : remove **_core_** protection
p.....p.....**_plugin_**..!!!
(为什么满脑子都是administrator和尤某某在塔顶的床上的场面)
coreplugin....啊...好污....
呃...好像是好了
嗯是好了。
辛苦@GPBeta

**Comment by visualDust** [comment]
```（不过作为一个角度刁钻的用户估计我一定会搞出些新毛病来...）```

**Comment by cxx1234** [comment]
![屏幕截图(23)](https://user-images.githubusercontent.com/4215066/56971331-9d9e2200-6b9b-11e9-97f4-81e37906011e.png)
现在出现了这个问题...不能编辑这些菜单项(￣▽￣)"

**Comment by visualDust** [comment]
在设置里把锁定关掉。

**Comment by visualDust** [comment]
@cxx1234 我开了一个新issue
![点击进入使用问题的issue](https://github.com/NERvGear/SAO-Utils/issues/4)
这些使用问题放到那里面去吧

**Comment by cxx1234** [comment]
😂好吧没事了，我把那个 Comment 删了吧

**Comment by visualDust** [comment]
噗

**Comment by visualDust** [comment]
真 · 禁忌之《ISSUE成了聊天区》
