### ISSUE TITLE
引入的顶框在重开软件后不在原先位置

### ISSUE THREAD

**Issue by GaoQiTa** [NERvGear/SAO-Utils#23]
![QQ截图20200314194248](https://user-images.githubusercontent.com/62174679/76681247-05caea80-662c-11ea-8765-2da895688ce2.png)
像这样的情况，每回启动都要手动的重新移动到上面

**Comment by GPBeta** [comment]
是不是图片有太大范围在屏幕外面了

**Comment by GaoQiTa** [comment]
> 是不是图片有太大范围在屏幕外面了

顶框确实超出屏幕了（两边都超了），底框只超了右边但没有错位=A=
