### ISSUE TITLE
sao菜单无法启动

### ISSUE THREAD

**Issue by NoEx1t** [NERvGear/SAO-Utils#24]
当您第一次在PC上启动程序时，一切正常，但是当您第一次调用菜单后第二天启动pc时，菜单无法打开，并出现关于坚不可摧的物体的题词。.. 有一次，以一种意想不到的方式，一切都开始工作，当程序重新启动时，一切都回到了源头。

**Comment by GPBeta** [comment]
Please check that at least one of these plugins are enabled:
- SAO Theme
- GGO Theme

**Comment by NoEx1t** [comment]
我不知道如何检查它我不是很聪明(((

**Comment by GPBeta** [comment]
![sao-utils-plugins](https://user-images.githubusercontent.com/13177262/78400964-4239a700-762a-11ea-880e-cc7359e0c4cc.png)
Save & Restart.

**Comment by NoEx1t** [comment]
多謝。
