### ISSUE TITLE
番剧资源

### ISSUE THREAD

**Issue by ZHSHZH** [NERvGear/SAO-Utils#33]
为什么2020春夏冬都有，唯独没用秋季番剧资源啊

**Comment by GPBeta** [comment]
因为 1 月份是冬......

**Comment by ZHSHZH** [comment]
> 因为 1 月份是冬......

我的意思是十月档番剧时间表是没有了吗QAQ

**Comment by GPBeta** [comment]
现在好了，刷新即可。

**Comment by SeasonG-CN** [comment]
> 因为 1 月份是冬......

**对不起,有点戳笑点……**
