### ISSUE TITLE
AOB / any other business / 任何使用上的问题

### ISSUE THREAD

**Issue by visualDust** [NERvGear/SAO-Utils#4]

**Comment by misaka12543** [comment]
### The "Extension" option in the information panel settings of the main menu cannot be selected.
Or is this feature still under development?

**Comment by GPBeta** [comment]
> The "Extension" option in the information panel settings of the main menu cannot be selected.
> Or is this feature still under development?

Yes, it's not available currently.

**Comment by GPBeta** [comment]
Please do not open all-inclusive issues.
请不要提交包罗万有的问题。
