### ISSUE TITLE
一些网络插件和图片会跑到应用界面上面，要怎么解决

### ISSUE THREAD

**Issue by SSDJSZM666** [NERvGear/SAO-Utils#45]
![QQ截图20210821223502](https://user-images.githubusercontent.com/63944869/130325182-b5be0aef-b16b-4496-9a58-226bac4564ff.png)

**Comment by SeasonG-CN** [comment]
**检查一下是不是置顶了**

**Comment by SSDJSZM666** [comment]
哪里可以看有没有置顶

**Comment by SSDJSZM666** [comment]
问题已经解决了，要打开挂件菜单然后点击那个针的图标就好了
