### ISSUE TITLE
【建议】能否在开机启动时不关联 Steam 启动

### ISSUE THREAD

**Issue by vzcrab** [NERvGear/SAO-Utils#47]
可以参考 Wallpaper，打开不用关联 Steam，只在需要时启动 Steam，如访问创意工坊。

除此之外还有一个重要原因，Steam 启动登录时，会因网络问题会卡启动界面和重复登录，导致每次启动 SAO Utils 时有点麻烦。

**Comment by GPBeta** [comment]
首选项-常规-取消勾选“启用 Steam 功能即可”
开机启动默认不会带起 Steam

**Comment by vzcrab** [comment]
好了，谢谢
