### ISSUE TITLE
EXP版天气炸了

### ISSUE THREAD

**Issue by Ayuyi** [NERvGear/SAO-Utils#62]
大佬什么时候修复exp版的天气啊 @GPBeta

**Comment by GPBeta** [comment]
见 https://github.com/NERvGear/SAO-Utils/issues/16#issuecomment-591353305

**Comment by Ayuyi** [comment]
> 见 [#16 (comment)](https://github.com/NERvGear/SAO-Utils/issues/16#issuecomment-591353305)

就是用这个了解的文件替换也不行啊(⋟﹏⋞)

**Comment by Ayuyi** [comment]
> 见 [#16 (comment)](https://github.com/NERvGear/SAO-Utils/issues/16#issuecomment-591353305)

就是用了这个链接的exp版天气补丁也不行(⋟﹏⋞)

**Comment by GPBeta** [comment]
再次修复该问题，请在原帖下载。

**Comment by Ayuyi** [comment]
> 再次修复该问题，请在原帖下载。

好的，感谢大佬修复，辛苦了(*˘︶˘*).。.:*♡
