### ISSUE TITLE
NERvGear已经停止

### ISSUE THREAD

**Issue by Kchenyuhang** [NERvGear/SAO-Utils#70]
启动之后，有一个登录界面，刚点击输入框就报错了
[call_stack.log](https://github.com/NERvGear/SAO-Utils/files/14165239/call_stack.log)
[mini_dump.dmp](https://github.com/NERvGear/SAO-Utils/files/14165241/mini_dump.dmp)

**Comment by GPBeta** [comment]
退出 SAO Utils 后在 Steam 检查一下文件完整性。

**Comment by GPBeta** [comment]
应该是切输入法输入中文的时候崩溃对吧？
Steam 刚刚推送了一个更新，退出 SAO Utils 并且重启 Steam 之后安装更新看看有没有修复。

**Comment by Kchenyuhang** [comment]
今天重新下载了一边，问题解决了
