### ISSUE TITLE
运行SAO Utils 2导致显卡驱动异常？

### ISSUE THREAD

**Issue by Muska-Ami** [NERvGear/SAO-Utils#72]
环境为 Windows 11 Pro 23H2
显卡为 AMD Radeon RX 580 2048SP
显卡驱动已为最新

在运行SAO Utils 2不久后电脑画面便不再变化，一直卡死
有时候会卡出显卡的错误报告工具，具体原因不确定
实测不打开SAO Utils 2并不会产生这种问题，所以推测可能是SAO Utils 2存在相关问题

**Comment by GPBeta** [comment]
请从【首选项 - 关于 - Bug 反馈... - 生成报告】复制系统和程序基本信息并粘贴到评论

**Comment by Muska-Ami** [comment]
[19 Jun 2024 05:07:34 +0800]

* System Information *
Host Name               花火のPC
OS Name                 Windows 10 Pro 2009
OS Version              10.0.22631
OS Path                 C:\Windows
System Type             x86_64
System Locale           zh_CN
CPU                     Intel(R) Xeon(R) CPU E5-2666 v3 @ 2.90GHz
GPU                     ANGLE (AMD Radeon RX 580 2048SP Direct3D11 vs_5_0 ps_5_0) / DComp
User                    25496

* Software Information *
Application             SAO Utils 2
Code                    Progressive
Version                 1.6.0
Platform                x64
Home                    D:/Program Files (x86)/Steam/steamapps/common/SAO Utils 2
Path                    D:/Program Files (x86)/Steam/steamapps/common/SAO Utils 2/win64
Locale                  zh_CN
Preferred Locale        
Available Locales       en,es,ja,ru,tr,zh,zh_TW
Process Elevated        False
Cache Path Writable     True
Config Path Writable    True
Dump Path Writable      True
Storage Path Writable   True

* Package Information *
com.darkness.widget.azur-clock                      1.0.0     AER
com.freezer.widget.mikutap                          1.0.0     AER
com.gpbeta.data.pdh                                 1.0.0     AER
com.gpbeta.data.sensor                              1.2.0     AER
com.gpbeta.data.weather                             1.1.0     AER
com.gpbeta.data.wmi                                 1.0.0     AER
com.gpbeta.mail-box                                 1.0.4     AER
com.gpbeta.media                                    1.3.2     AER
com.gpbeta.my.character-image                       1.0.0     AER
com.gpbeta.theme.ggo                                1.0.3     AER
com.gpbeta.theme.sao                                1.0.5     AER
com.gpbeta.widget.advp-style                        1.0.1     AER
com.gpbeta.widget.bangumi                           1.0.4     AER
com.gpbeta.widget.eye-dropper                       1.0.0     AER
com.gpbeta.widget.hp-bar                            1.0.2     AER
com.gpbeta.widget.hud                               1.6.0     AER
com.gpbeta.widget.launch                            1.0.0     AER
com.gpbeta.widget.menu                              1.1.0     AER
com.gpbeta.widget.note                              1.0.0     AER
com.gpbeta.widget.web                               1.2.2     AER
com.misakayuuki.iconcol                             1.0.0     AER
darkness.widget.ageoclock                           1.2.5     AER
system                                              1.6.0     AER
top.mashiros.widget.advp                            1.4.4     AER
top.mashiros.widget.nclocks                         1.0.2     AER
ugc.steam.879849855.3258029809                      1.0.0-craft AER
ugc.steam.889909527.3164039273                      1.0.0-craft AER

**Comment by GPBeta** [comment]
尝试把【首选项 - 开发者模式 - 实验性功能 - DirectComposition API】选项关闭重启看看。

**Comment by Muska-Ami** [comment]
关闭后正常使用一段时间测试似乎没有问题了，感谢解答。

**Comment by GPBeta** [comment]
看来这个功能只有 Intel 核显能正常使用的……
